"""Add is_pinned to Conversation

Revision ID: a0acc499f880
Revises: 
Create Date: 2025-06-21 02:58:47.678082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0acc499f880'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_conversations_is_pinned'), ['is_pinned'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_is_pinned'))
        batch_op.drop_column('is_pinned')

    # ### end Alembic commands ###
